/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author welcome
 */
public class DeletePage extends javax.swing.JFrame {
    List<String> temsave = new ArrayList<>();
    List<String> temsaveselect = new ArrayList<>();
    int selectedrow, tellnovalue = 0;
    /**
     * Creates new form DeletePage
     */
    public DeletePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        RoomID = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setBackground(new java.awt.Color(153, 153, 153));
        btnSearch.setFont(new java.awt.Font("SimHei", 3, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(51, 51, 51));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 260, -1, -1));

        btnExit.setBackground(new java.awt.Color(153, 153, 153));
        btnExit.setFont(new java.awt.Font("SimHei", 3, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(51, 51, 51));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 490, -1, -1));

        RoomID.setBackground(new java.awt.Color(204, 204, 204));
        RoomID.setFont(new java.awt.Font("Sitka Text", 2, 12)); // NOI18N
        RoomID.setForeground(new java.awt.Color(102, 102, 102));
        RoomID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Click Search to get RoomID..." }));
        RoomID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoomIDActionPerformed(evt);
            }
        });
        getContentPane().add(RoomID, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 300, -1));

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("SimHei", 3, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(51, 51, 51));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 490, -1, -1));

        btnDelete.setBackground(new java.awt.Color(153, 153, 153));
        btnDelete.setFont(new java.awt.Font("SimHei", 3, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(51, 51, 51));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, -1, -1));

        Table.setBackground(new java.awt.Color(204, 204, 204));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Table);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 780, 150));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("                                                                            Delete Page");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 840, 50));

        jLabel5.setFont(new java.awt.Font("Verdana", 2, 14)); // NOI18N
        jLabel5.setText("Enter Room ID to  delete details:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, 20));

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 840, 360));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/background.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int n = JOptionPane.showConfirmDialog(null,"Would you like to terminate?", "Terminate System", JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        ManagePage manage = new ManagePage ();
        manage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        ArrayList<String> listroomid = new ArrayList<>();
        try {
            File files = new File("room.txt");
            Scanner inputfile = new Scanner(files);
            while (inputfile.hasNextLine()) {
                String[] list = inputfile.nextLine().split(", ");
                listroomid.add(list[0]);
            }
            inputfile.close();
            RoomID.removeAllItems();
            RoomID.addItem("Choose the Room ID...");
            for (String each : listroomid) {
            RoomID.addItem(each);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ModifyPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void RoomIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoomIDActionPerformed
        String filepath = "booking.txt";
        File file = new File(filepath);
        String [] firstline ={"Room_ID","Customer_Name","IC", "Email", "Contact", "Number_of_daystay", "Check-in_date", "Check-out_date"};
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            DefaultTableModel model = (DefaultTableModel)Table.getModel();
            model.setColumnIdentifiers(firstline);
            model.setRowCount(0);
        } catch (Exception ex) {
            Logger.getLogger(ModifyPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        String selectedroom;
        selectedroom = String.valueOf(RoomID.getSelectedItem());
        try{
            File verify = new File("booking.txt");
            Scanner verifyfile = new Scanner(verify);
            DefaultTableModel model = (DefaultTableModel)Table.getModel();
            temsave.clear();
            model.setColumnIdentifiers(firstline);
            while(verifyfile.hasNextLine()){
                String line = verifyfile.nextLine();
                String[] list = line.split(",\\s*");
                if (list[0].equals(selectedroom)){
                    model.addRow(list);
                } else {
                    temsave.add(line);
                }
            }
            verifyfile.close();
        }catch(FileNotFoundException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_RoomIDActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        selectedrow = Table.getSelectedRow();
        if(selectedrow >= 0){
            DefaultTableModel model = (DefaultTableModel)Table.getModel();

            int numRows = model.getRowCount();
            temsaveselect.clear();
            for (int i = 0; i < numRows; i++) {
                if (!Table.isRowSelected(i)) {
                    // These row is not selected
                    String aa = model.getValueAt(i, 0).toString();
                    String bb = model.getValueAt(i, 1).toString();
                    String cc = model.getValueAt(i, 2).toString();
                    String dd = model.getValueAt(i, 3).toString();
                    String ee = model.getValueAt(i, 4).toString();
                    String ff = model.getValueAt(i, 5).toString();
                    String gg = model.getValueAt(i, 6).toString();
                    String hh = model.getValueAt(i, 7).toString();
                    String thisall = aa + ", " + bb + ", " + cc + ", " + dd + ", " + ee + ", " + ff + ", " + gg + ", " + hh + ", ";
                    temsaveselect.add(thisall);
                } 
            }
            tellnovalue = 1;
        }
    }//GEN-LAST:event_TableMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (tellnovalue > 0){   
            String filepath = "booking.txt";
            try (FileWriter writer = new FileWriter(filepath, false)) {
                for (String eachcorrect : temsave){
                    writer.write(eachcorrect + "\n");
                }
                for (String eachprint : temsaveselect){
                    writer.write(eachprint + "\n");
                }
                writer.close();
                JOptionPane.showMessageDialog(null,"Delete success.","Success",JOptionPane.INFORMATION_MESSAGE);
                ManagePage go = new ManagePage();
                go.setVisible(true);
                this.setVisible(false);
            } catch (IOException e) {
            }
        }else{
            JOptionPane.showMessageDialog(null, "Could not delete the details due to no selected data for delete" ,"Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeletePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeletePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeletePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeletePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeletePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> RoomID;
    private javax.swing.JTable Table;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
