/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment;

import javax.swing.JOptionPane;

/**
 *
 * @author welcome
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBooking = new javax.swing.JButton();
        txtManage = new javax.swing.JButton();
        txtExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("                                    Home Page");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 420, 50));

        txtBooking.setBackground(new java.awt.Color(153, 153, 153));
        txtBooking.setFont(new java.awt.Font("SimHei", 3, 18)); // NOI18N
        txtBooking.setForeground(new java.awt.Color(51, 51, 51));
        txtBooking.setText("Booking");
        txtBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookingActionPerformed(evt);
            }
        });
        getContentPane().add(txtBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 290, 50));

        txtManage.setBackground(new java.awt.Color(153, 153, 153));
        txtManage.setFont(new java.awt.Font("SimHei", 3, 18)); // NOI18N
        txtManage.setForeground(new java.awt.Color(51, 51, 51));
        txtManage.setText("Manage");
        txtManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtManageActionPerformed(evt);
            }
        });
        getContentPane().add(txtManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 290, 50));

        txtExit.setBackground(new java.awt.Color(153, 153, 153));
        txtExit.setFont(new java.awt.Font("SimHei", 3, 12)); // NOI18N
        txtExit.setForeground(new java.awt.Color(51, 51, 51));
        txtExit.setText("Exit");
        txtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExitActionPerformed(evt);
            }
        });
        getContentPane().add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, -1, -1));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 420, 290));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assignment/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExitActionPerformed
        int n = JOptionPane.showConfirmDialog(null,"Would you like to terminate?", "Terminate System", JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION)
        System.exit(0);
    }//GEN-LAST:event_txtExitActionPerformed

    private void txtBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookingActionPerformed
        BookingPage page1 = new BookingPage();
        page1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_txtBookingActionPerformed

    private void txtManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtManageActionPerformed
        ManagePage page2 = new ManagePage();
        page2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_txtManageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton txtBooking;
    private javax.swing.JButton txtExit;
    private javax.swing.JButton txtManage;
    // End of variables declaration//GEN-END:variables
}
